FROM ubuntu:22.04
ENV NODE_ENV=production
WORKDIR /app

RUN apt-get update
RUN apt-get install -y language-pack-ja-base language-pack-ja locales tzdata
RUN locale-gen ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV TZ=Asia/Tokyo
ENV LANGUAGE=ja_JP:ja
ENV PS1="softPrac %d # "

RUN apt-get update
RUN apt-get install -y curl make less gcc g++ default-jdk dumb-init zsh

RUN curl -fsSL https://deb.nodesource.com/setup_20.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt-get install nodejs -y
RUN apt upgrade -y
RUN npm install -g npm yarn

COPY backend/ ./backend/
COPY package.json ./package.json

RUN yarn install --prod --frozen-lockfile

EXPOSE 3001

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
#CMD ["sh"]
CMD ["node_modules/.bin/tsx", "backend/bin/www.ts"]
