FROM node:iron
ENV NODE_ENV=production
WORKDIR /app

RUN apt update
RUN apt install default-jdk dumb-init zsh -y
RUN apt upgrade -y

COPY backend/ ./backend/
COPY package.json ./package.json

RUN yarn install --prod --frozen-lockfile

EXPOSE 3001

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
#CMD ["sh"]
CMD ["node_modules/.bin/tsx", "backend/bin/www.ts"]


